TERM environment variable not set.
Inside INIT
concurrent is :0
Inside INVOKER.PY 


('192.168.182.128', 'seq_def', '443', '1', '-T4 -A -v -Pn -n', '728', 'g-start', '1afb8988-66d3-11e7-9483-08002722e7b2', 'Paladion_practice', '0')
Reached !!!@@@###
('(192.168.182.128', 'seq_def', '443', '1', '-T4 -A -v -Pn -n', '728', 'g-start', '1afb8988-66d3-11e7-9483-08002722e7b2', 'Paladion_practice)')


 Hello world 


The mode recieved is :g-start and profile at main : 2
[34m[+]Starting SCAN[0m
Started
(1)--About to make bulk enteries - #Ip:1
in else
Started
ended
Ended
In begning the number of threads are :1
In begning the threads alive are :[<_MainThread(MainThread, started 139752056194704)>]
started
Started DH
Ended DH
Ended


[31m----------------------------------------------[0m
None
Starting : 1Threads for ['192.168.182.128']Hosts
[31m----------------------------------------------[0m
None


[32m******************************************************************************************************************************************
[0mCurrent thread count : 1
The threads enumerate returned are : [<_MainThread(MainThread, started 139752056194704)>][32m
******************************************************************************************************************************************[0m
Inside INIT
Started Simple acanner
Started

Started thread for IP :192.168.182.128 --> Thread is : <Thread(Thread-1, started daemon 139751947958016)>
Ended
Reached port scanner module with record id --> 2536
Starting the scan with the switch :-T4 -A -v -Pn -n
Reached Debug 1
Reached Debug 2
Up host status is :1
Reached Debug 3
[31m----------------------------------------------[0m
Reached Debug 4
Result for IP : 192.168.182.128
Protocol : TCP
Reached Debug 5
[34mport : [33m443 	 [32mclosed 	[31mhttps[0m
[31m----------------------------------------------[0m
Reached Debug 6
Started
Stopped
Reached Debug 8


 Finished subprocess for ip 192.168.182.128 and Process : <Process(Process-1, stopped)>
Ended Simple acanner


Thread ended with host ip -192.168.182.128


**Pooling started :**
[31m----------------------------------------------[0m
None
Polling 
 Threads remaining are :[<_MainThread(MainThread, started 139752056194704)>, <_DummyThread(Dummy-2, started daemon 139752121865984)>]

[31m----------------------------------------------[0m
None
Obtained dummy thread <_DummyThread(Dummy-2, started daemon 139752121865984)>
Only dummy threads are alive-Attempting to close
Started
Ended
Active Threads are only 1 --Scan about to finish --Threads remaining are :[<_MainThread(MainThread, started 139752056194704)>, <_DummyThread(Dummy-2, started daemon 139752121865984)>]
Active Threads are only 1 --Scan about to finish --Threads remaining are :[<_MainThread(MainThread, started 139752056194704)>, <_DummyThread(Dummy-2, started daemon 139752121865984)>]
Reached here as well !!!
# of threads Alive are :2

Now stopping and saving Global Project Id : 728

Started
Ended
Launching clear logs !!!
Clearing old logs !!!!! with status -->complete


The logs are not clear :

 Clearing them Now ..................


Clearing Logs now inside clear logs !!
Cleared all logs !!
The logs are finally cleared !!!
Time taken in seconds : 119.227329016
Inside INIT
Inside INIT
INVOKED Driver meta main with record_list : [] and  concurrent status : False and skip_init_check status as :False and continue =False





P_id ---> 728


 Project id is :	728


valid projects are ['728']
IN exists with Pid728
Connection init done()
Logg printed
here#@@
0
Initialising parent directory 
INitialised
Hello
here reached 
I am in parse and process


 Inside insert IPexploits --



[32m[+] Launching configuration ....[0m
success


About to return now !!!
success fully done till now
folder name is : /root/Django-projects/Dictator/Dictator_service





Inside update --Obtained process id is ->15130  and project_id is : 728
Concurrent is false and updating with above values
ended
Stopped
Successfully launched exploits in seq-def mode.Reffer to exploits logs from here on 
